selenium: package.json cleanup
There's a patch for core moving from dot to spec reporter. FileImporter
tests for that core patch are failing with:

Error: Couldn't find plugin "dot" reporter, neither as wdio scoped
package "@wdio/dot-reporter" nor as community package
"wdio-dot-reporter".

See https://gerrit.wikimedia.org/r/c/mediawiki/core/+/680345

Install missing package: @wdio/dot-reporter.
Remove unnneded packages: @wdio/spec-reporter, wdio-junit-reporter.

Bug: T280331
Change-Id: I66498152707504912700976976909ddcc0f51a78